// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWeb.Data;

namespace MyWeb.Migrations
{
    [DbContext(typeof(Contents))]
    [Migration("20201228183250_Why_Did_You_Decide_To_Create_This_Website_or_App")]
    partial class Why_Did_You_Decide_To_Create_This_Website_or_App
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MyWeb.Models.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("What_Are_You_Passionate_About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("What_To_Do")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Who_Are_You_Making_This_For")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Why_Did_You_Decide_To_Create_This_Website_or_App")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
